# http://materialdesignicons.com/cdn/7.4.47/
# Icons used by the music dashboard and setup screens (device/lvgl.yaml).
# MaterialDesign-Webfont TTF uses codepoints in the PUA (U+F0xxx).

font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 40
    bpp: 4
    glyphs:
      - "\U000F040A"  # mdi-play
      - "\U000F03E4"  # mdi-pause
      - "\U000F0415"  # mdi-plus
      - "\U000F0374"  # mdi-minus
      - "\U000F05A9"  # mdi-wifi
      - "\U000F07D0"  # mdi-home-assistant
      - "\U000F0118"  # mdi-cast
      - "\U000F0565"  # mdi-shield-check
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font_large
    size: 50
    bpp: 4
    glyphs:
      - "\U000F040A"  # mdi-play
      - "\U000F03E4"  # mdi-pause
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font_setup
    size: 64
    bpp: 4
    glyphs:
      - "\U000F05A9"  # mdi-wifi
      - "\U000F07D0"  # mdi-home-assistant
      - "\U000F0118"  # mdi-cast
      - "\U000F0565"  # mdi-shield-check

substitutions:
  play:          "\U000F040A"
  pause:         "\U000F03E4"
  icon_plus:     "\U000F0415"
  icon_minus:    "\U000F0374"
  icon_wifi:     "\U000F05A9"
  icon_ha:       "\U000F07D0"
  icon_cast:     "\U000F0118"
  icon_shield:   "\U000F0565"
