substitutions:
  name: "music-dashboard"                          # Device hostname (lowercase, hyphens only)
  friendly_name: "Music Dashboard"                  # Name shown in Home Assistant
  room: "Living Room"                               # Home Assistant area
  media_player: "media_player.CHANGE_ME"            # Your media player entity ID

wifi:
  ap:

packages:
  setup:
    url: https://github.com/jtenniswood/esphome-media-player/
    files: [guition-esp32-s3-4848s040/device/device.yaml,
            guition-esp32-s3-4848s040/device/sensors.yaml,
            guition-esp32-s3-4848s040/device/lvgl.yaml,
            guition-esp32-s3-4848s040/addon/backlight.yaml,
            guition-esp32-s3-4848s040/addon/time.yaml,
            guition-esp32-s3-4848s040/addon/network.yaml,
            guition-esp32-s3-4848s040/addon/music.yaml,
            guition-esp32-s3-4848s040/assets/fonts.yaml,
            guition-esp32-s3-4848s040/assets/icons.yaml,
            guition-esp32-s3-4848s040/theme/button.yaml]
    refresh: 1sec
