packages:
  core: !include guition-esp32-s3-4848s040.yaml

esphome:
  name_add_mac_suffix: true
  project:
    name: jtenniswood.music-dashboard
    version: dev

dashboard_import:
  package_import_url: github://jtenniswood/esphome-media-player/guition-esp32-s3-4848s040/guition-esp32-s3-4848s040.yaml@main
