substitutions:
  media_player: ""
  tv_media_player: ""

packages:
  music: !include addon/music.yaml
  backlight: !include addon/backlight.yaml
  time_sync: !include addon/time.yaml
  network: !include addon/network.yaml
  fonts: !include assets/fonts.yaml
  icons: !include assets/icons.yaml
  device: !include device/device.yaml
  media_player_select: !include device/media_player_select.yaml
  sensors: !include device/sensors.yaml
  tv_sensors: !include device/tv_sensors.yaml
  lvgl: !include device/lvgl.yaml
  button: !include theme/button.yaml