# =============================================================================
# NETWORK & WIFI SETUP PROMPT
# =============================================================================
# WiFi diagnostics and a first-boot setup screen that tells the user to
# connect to the device's hotspot to configure WiFi credentials.
# =============================================================================

wifi:
  on_connect:
    - lvgl.widget.hide: wifi_setup_prompt
    - lvgl.widget.show: ha_setup_prompt
  on_disconnect:
    - lvgl.widget.show: wifi_setup_prompt
    - lvgl.widget.hide: ha_setup_prompt

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          std::string name = App.get_name();
          std::string text = "Connect to the WiFi hotspot\n'" + name + "'\nto configure your network";
          lv_label_set_text(id(wifi_setup_instructions), text.c_str());

# Online Status
binary_sensor:
  - platform: status
    name: "Online"
    id: ink_ha_connected
    icon: mdi:check-network

sensor:
# Wifi Signal Strength
  - platform: wifi_signal
    name: "Wifi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true

# Wifi Signal Strength
  - platform: copy
    source_id: wifi_signal_db
    name: "Wifi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    icon: mdi:wifi
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
# Ip Address
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network