# =============================================================================
# NETWORK & WIFI SETUP PROMPT
# =============================================================================
# WiFi diagnostics and a first-boot setup screen that tells the user to
# connect to the device's hotspot to configure WiFi credentials.
# =============================================================================

globals:
  - id: boot_grace_period
    type: bool
    initial_value: 'true'

wifi:
  on_connect:
    - lambda: |-
        lv_bar_set_value(id(loading_progress_bar), 100, LV_ANIM_OFF);
    - delay: 800ms
    - lvgl.widget.hide: loading_screen
    - lvgl.widget.hide: wifi_setup_prompt
    - if:
        condition:
          lambda: 'return !id(device_has_been_setup) && !id(boot_grace_period);'
        then:
          - lvgl.widget.show: ha_setup_prompt
  on_disconnect:
    - if:
        condition:
          lambda: 'return !id(device_has_been_setup) && !id(boot_grace_period);'
        then:
          - lvgl.widget.show: wifi_setup_prompt
    - lvgl.widget.hide: ha_setup_prompt

esphome:
  on_boot:
    - priority: -200
      then:
        - lambda: |-
            lv_bar_set_value(id(loading_progress_bar), 25, LV_ANIM_OFF);
    - priority: -100
      then:
        - lambda: |-
            lv_bar_set_value(id(loading_progress_bar), 50, LV_ANIM_OFF);
        - lambda: |-
            std::string name = App.get_name();
            std::string wifi_text = "Connect to the WiFi hotspot\n'" + name + "'\nto configure your network";
            lv_label_set_text(id(wifi_setup_instructions), wifi_text.c_str());
            std::string ha_text = "Add '" + name + "' in\nSettings > Devices > ESPHome";
            lv_label_set_text(id(ha_setup_instructions), ha_text.c_str());
            std::string actions_text = "In Home Assistant, go to\nSettings > Devices > ESPHome\nFind '" + name + "' and enable\n'Allow the device to perform\nHome Assistant actions'";
            lv_label_set_text(id(actions_instructions), actions_text.c_str());
        - delay: 10s
        - lambda: 'id(boot_grace_period) = false;'
        - lvgl.widget.hide: loading_screen
        - if:
            condition:
              and:
                - lambda: 'return !id(device_has_been_setup);'
                - not:
                    wifi.connected:
            then:
              - lvgl.widget.show: wifi_setup_prompt
        - if:
            condition:
              and:
                - lambda: 'return !id(device_has_been_setup);'
                - wifi.connected:
                - lambda: |-
                    return esphome::api::global_api_server == nullptr
                        || !esphome::api::global_api_server->is_connected();
            then:
              - lvgl.widget.show: ha_setup_prompt

# Online Status
binary_sensor:
  - platform: status
    name: "Online"
    id: ink_ha_connected
    icon: mdi:check-network

sensor:
# Wifi Signal Strength
  - platform: wifi_signal
    name: "Wifi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true

# Wifi Signal Strength
  - platform: copy
    source_id: wifi_signal_db
    name: "Wifi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    icon: mdi:wifi
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
# Ip Address
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network