substitutions:
  icon_font: icon_font
  text_font: roboto19_font
  button_on_color: "0xFF8C00"
  button_text_color: "0xFFFFFF"
  button_control_color: "0x313131"
  padding: 12px
  radius: 8px

lvgl:
  style_definitions:
    - id: control_round
      bg_color: $button_control_color
      radius: 48px

  theme:
    button:
      text_font: $text_font
      scroll_on_focus: false
      radius: $radius
      pad_all: $padding
      shadow_width: 0
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
    arc:
      arc_color: 0x333333
      arc_width: 12
      indicator:
        arc_color: 0x999999
        arc_width: 12
      knob:
        bg_color: 0xFFFFFF
        radius: 14
    bar:
      indicator:
        bg_color: 0xFFFFFF
        radius: 0
      main:
        bg_color: 0x000000
        bg_opa: 50%
        radius: 0
