# =============================================================================
# SENSORS - Music dashboard (media_player.office)
# =============================================================================
# Subscribes to media_player attributes and updates LVGL labels, bar, image,
# and play/pause icon. To use a different entity, override in your main YAML
# with a package override or use a local copy and set entity_id.
# Album art base URL: http://192.168.1.30:8123 (path from HA already includes token).
# =============================================================================

# Store last HA position and time so we can estimate elapsed time between updates
# (HA/Sonos often only push media_position every 5–10s; we tick every 1s)
globals:
  - id: last_media_position
    type: float
    initial_value: '0.0'
  - id: last_position_timestamp
    type: int
    initial_value: '0'
  - id: is_tv_mode
    type: bool
    initial_value: 'false'

# Refresh progress bar and elapsed time every second; when playing, estimate
# position from last HA update + elapsed time so the clock moves smoothly
interval:
  - interval: 1s
    then:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode);'
          then:
            - lvgl.label.update:
                id: media_time_label
                text: !lambda |-
                  float pos = id(last_position_timestamp) != 0 && id(media_position_sensor).has_state()
                    ? id(media_position_sensor).state : id(last_media_position);
                  if (id(media_player_state_sensor).state == "playing") {
                    auto t = id(sntp_time).now();
                    if (t.is_valid() && id(last_position_timestamp) != 0) {
                      pos = id(last_media_position) + (t.timestamp - id(last_position_timestamp));
                      if (pos < 0) pos = 0;
                      float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
                      if (dur > 0 && pos > dur) pos = dur;
                    }
                  }
                  float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
                  int e = (int)pos; if (e < 0) e = 0;
                  int rem = (int)(dur - pos); if (rem < 0) rem = 0;
                  char buf[24];
                  snprintf(buf, sizeof(buf), "%d:%02d / -%d:%02d", e / 60, e % 60, rem / 60, rem % 60);
                  return std::string(buf);
            - lvgl.bar.update:
                id: media_progress_bar
                value: !lambda |-
                  float pos = id(last_position_timestamp) != 0 && id(media_position_sensor).has_state()
                    ? id(media_position_sensor).state : id(last_media_position);
                  if (id(media_player_state_sensor).state == "playing") {
                    auto t = id(sntp_time).now();
                    if (t.is_valid() && id(last_position_timestamp) != 0) {
                      pos = id(last_media_position) + (t.timestamp - id(last_position_timestamp));
                      if (pos < 0) pos = 0;
                      float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
                      if (dur > 0 && pos > dur) pos = dur;
                    }
                  }
                  float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
                  if (dur > 0) return (int)((pos / dur) * 100.0f);
                  return 0;

# ---------------------------------------------------------------------------
# MODE-SWITCH SCRIPTS
# ---------------------------------------------------------------------------
# Reusable scripts to switch between TV mode and music mode.
# Called from media_source_sensor (primary) and as fallback from
# media_entity_picture_sensor so the display switches to music mode
# when album art appears, even if the source attribute stays "TV".
# ---------------------------------------------------------------------------
script:
  - id: enter_tv_mode
    then:
      - lambda: 'id(is_tv_mode) = true;'
      - lvgl.widget.hide: album_art_background_widget
      - lvgl.widget.hide: media_title_label
      - lvgl.widget.hide: media_artist_label
      - lvgl.widget.hide: media_play_pause_button
      - lvgl.widget.hide: media_time_label
      - lvgl.widget.hide: media_progress_bar
      - lvgl.widget.show: tv_source_label
  - id: enter_music_mode
    then:
      - lambda: 'id(is_tv_mode) = false;'
      - lvgl.widget.show: album_art_background_widget
      - lvgl.widget.show: media_title_label
      - lvgl.widget.show: media_artist_label
      - lvgl.widget.show: media_play_pause_button
      - lvgl.widget.show: media_time_label
      - lvgl.widget.show: media_progress_bar
      - lvgl.widget.hide: tv_source_label

text_sensor:
  - platform: homeassistant
    entity_id: ${media_player}
    id: media_title_sensor
    attribute: media_title
    on_value:
      # Track changed (skip/next) — reset position to 0 and stamp the current
      # time so the 1-second interval timer can immediately start counting
      # from 0 for the new track (avoids stale timestamp = 0 blocking updates).
      - lambda: |-
          id(last_media_position) = 0.0f;
          auto t = id(sntp_time).now();
          if (t.is_valid()) {
            id(last_position_timestamp) = t.timestamp;
          }
      - lvgl.label.update:
          id: media_title_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'
      - lvgl.label.update:
          id: media_time_label
          text: "0:00 / -0:00"
      - lvgl.bar.update:
          id: media_progress_bar
          value: 0

  - platform: homeassistant
    entity_id: ${media_player}
    id: media_artist_sensor
    attribute: media_artist
    on_value:
      - lvgl.label.update:
          id: media_artist_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'

  - platform: homeassistant
    entity_id: ${media_player}
    id: media_entity_picture_sensor
    attribute: entity_picture
    on_value:
      - if:
          condition:
            lambda: 'return !x.empty();'
          then:
            - online_image.set_url:
                id: album_art_background
                url: !lambda |-
                  std::string path = x;
                  while (!path.empty() && (path.back() == '\n' || path.back() == '\r' || path.back() == ' ')) path.pop_back();
                  return std::string("${home_assistant_url}") + path;
            # Album art appeared — if we're in TV mode, music is now playing.
            - if:
                condition:
                  lambda: 'return id(is_tv_mode);'
                then:
                  - script.execute: enter_music_mode

  - platform: homeassistant
    entity_id: ${media_player}
    id: media_player_state_sensor
    on_value:
      - if:
          condition:
            lambda: 'return x == "playing";'
          then:
            - script.stop: backlight_wake_timeout
            - lvgl.resume:
            - lvgl.widget.hide:
                id: media_play_icon
            - lvgl.widget.show:
                id: media_pause_icon
            - light.turn_on:
                id: backlight
                brightness: 100%
          else:
            - lvgl.widget.show:
                id: media_play_icon
            - lvgl.widget.hide:
                id: media_pause_icon
            - script.execute: backlight_wake_timeout

  - platform: homeassistant
    entity_id: ${media_player}
    id: media_source_sensor
    attribute: source
    on_value:
      - if:
          condition:
            lambda: 'return x == "TV";'
          then:
            - script.execute: enter_tv_mode
          else:
            - script.execute: enter_music_mode

sensor:
  - platform: homeassistant
    entity_id: ${media_player}
    id: media_duration_sensor
    attribute: media_duration
    on_value:
      - lvgl.label.update:
          id: media_time_label
          text: !lambda |-
            int d = (int)x; if (d < 0) d = 0;
            float pos = id(last_media_position);
            int e = (int)pos; if (e < 0) e = 0;
            int rem = d - e; if (rem < 0) rem = 0;
            char buf[24];
            snprintf(buf, sizeof(buf), "%d:%02d / -%d:%02d", e / 60, e % 60, rem / 60, rem % 60);
            return std::string(buf);

  - platform: homeassistant
    entity_id: ${media_player}
    id: media_position_sensor
    attribute: media_position
    on_value:
      - lambda: |-
          id(last_media_position) = x;
          auto t = id(sntp_time).now();
          if (t.is_valid()) id(last_position_timestamp) = t.timestamp;
      - lvgl.label.update:
          id: media_time_label
          text: !lambda |-
            int e = (int)x; if (e < 0) e = 0;
            float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
            int d = (int)dur; if (d < 0) d = 0;
            int rem = d - e; if (rem < 0) rem = 0;
            char buf[24];
            snprintf(buf, sizeof(buf), "%d:%02d / -%d:%02d", e / 60, e % 60, rem / 60, rem % 60);
            return std::string(buf);
      - lvgl.bar.update:
          id: media_progress_bar
          value: !lambda |-
            float pos = x;
            float dur = id(media_duration_sensor).state;
            if (dur > 0) {
              return (int)((pos / dur) * 100.0f);
            }
            return 0;
