# =============================================================================
# SENSORS - Music dashboard
# =============================================================================
# Template sensors receive state from dynamic subscriptions managed by
# media_player_select.yaml. Updates LVGL labels, bar, image, and play/pause
# icon via on_value automations.
# Album art URL is built automatically from the HA API client's IP address;
# override home_assistant_url in substitutions for non-standard setups.
# =============================================================================

# Store last HA position and time so we can estimate elapsed time between updates
# (HA/Sonos often only push media_position every 5–10s; we tick every 1s)
globals:
  - id: ha_base_url
    type: std::string
    initial_value: '"http://homeassistant.local:8123"'
  - id: last_media_position
    type: float
    initial_value: '0.0'
  - id: last_position_timestamp
    type: int
    initial_value: '0'
  - id: title_received_once
    type: bool
    initial_value: 'false'
  - id: ha_position_epoch
    type: int
    initial_value: '0'

# Refresh progress bar and elapsed time every second; when playing, estimate
# position from last HA update + elapsed time so the clock moves smoothly
interval:
  - interval: 1s
    then:
      - lambda: |-
          bool tv = id(is_tv_mode);
          float dur = tv
              ? (id(tv_media_duration_sensor).has_state() ? id(tv_media_duration_sensor).state : 0.0f)
              : (id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f);
          bool playing = tv
              ? (id(tv_media_player_state_sensor).has_state() && id(tv_media_player_state_sensor).state == "playing")
              : (id(media_player_state_sensor).has_state() && id(media_player_state_sensor).state == "playing");

          float &last_pos    = tv ? id(last_tv_media_position)    : id(last_media_position);
          int   &last_ts     = tv ? id(last_tv_position_timestamp): id(last_position_timestamp);
          int   &pos_epoch   = tv ? id(tv_ha_position_epoch)      : id(ha_position_epoch);
          auto  *pos_sensor  = tv ? id(tv_media_position_sensor)  : id(media_position_sensor);

          float pos;
          auto t = id(ha_time).now();
          if (playing && t.is_valid() && pos_epoch != 0 && pos_sensor->has_state()) {
            pos = pos_sensor->state + (float)(t.timestamp - pos_epoch);
          } else if (playing && t.is_valid() && last_ts != 0) {
            pos = last_pos + (float)(t.timestamp - last_ts);
          } else {
            pos = pos_sensor->has_state() ? pos_sensor->state : last_pos;
          }
          if (pos < 0) pos = 0;
          if (dur > 0 && pos > dur) pos = dur;
          last_pos = pos;
      - lvgl.label.update:
            id: media_time_label
            text: !lambda |-
              bool tv = id(is_tv_mode);
              float pos = tv ? id(last_tv_media_position) : id(last_media_position);
              float dur = tv
                  ? (id(tv_media_duration_sensor).has_state() ? id(tv_media_duration_sensor).state : 0.0f)
                  : (id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f);
              int e = (int)pos; if (e < 0) e = 0;
              int rem = (int)(dur - pos); if (rem < 0) rem = 0;
              char buf[24];
              snprintf(buf, sizeof(buf), "%d:%02d / -%d:%02d", e / 60, e % 60, rem / 60, rem % 60);
              return std::string(buf);
      - lvgl.bar.update:
            id: media_progress_bar
            value: !lambda |-
              bool tv = id(is_tv_mode);
              float pos = tv ? id(last_tv_media_position) : id(last_media_position);
              float dur = tv
                  ? (id(tv_media_duration_sensor).has_state() ? id(tv_media_duration_sensor).state : 0.0f)
                  : (id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f);
              if (dur > 0) return (int)((pos / dur) * 100.0f);
              return 0;

script:
  # Auto-show track info on track change, then auto-hide after configured duration.
  # mode: restart ensures each new track resets the timer.
  - id: auto_hide_track_info
    mode: restart
    then:
      - if:
          condition:
            lambda: 'return id(is_ui_hidden);'
          then:
            - script.execute: toggle_ui
      - if:
          condition:
            lambda: 'return id(track_info_duration).state > 0;'
          then:
            - delay: !lambda 'return (uint32_t)(id(track_info_duration).state * 1000);'
            - if:
                condition:
                  lambda: |-
                    bool playing = id(is_tv_mode)
                        ? (id(tv_media_player_state_sensor).has_state() && id(tv_media_player_state_sensor).state == "playing")
                        : (id(media_player_state_sensor).has_state() && id(media_player_state_sensor).state == "playing");
                    return !id(is_ui_hidden) && playing;
                then:
                  - script.execute: toggle_ui

text_sensor:
  - platform: template
    id: media_title_sensor
    on_value:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode);'
          then:
            - script.execute: auto_hide_track_info
            - lvgl.widget.update:
                id: album_art_background_widget
                opa: 50%
            - lvgl.widget.hide: artwork_error_label
            - lvgl.label.update:
                id: media_title_label
                text: !lambda 'return x.empty() ? std::string("—") : x;'
            - if:
                condition:
                  lambda: 'return id(title_received_once);'
                then:
                  - lambda: |-
                      id(last_media_position) = 0.0f;
                      id(ha_position_epoch) = 0;
                      auto t = id(ha_time).now();
                      if (t.is_valid()) {
                        id(last_position_timestamp) = t.timestamp;
                      }
                  - lvgl.label.update:
                      id: media_time_label
                      text: "0:00 / -0:00"
                  - lvgl.bar.update:
                      id: media_progress_bar
                      value: 0
                else:
                  - lambda: 'id(title_received_once) = true;'

  - platform: template
    id: media_artist_sensor
    on_value:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode);'
          then:
            - lvgl.label.update:
                id: media_artist_label
                text: !lambda 'return x.empty() ? std::string("—") : x;'

  - platform: template
    id: media_entity_picture_sensor
    on_value:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode) && !x.empty();'
          then:
            - lvgl.widget.update:
                id: album_art_background_widget
                opa: 50%
            - lvgl.widget.hide: artwork_error_label
            - online_image.set_url:
                id: album_art_background
                url: !lambda |-
                  std::string path = x;
                  while (!path.empty() && (path.back() == '\n' || path.back() == '\r' || path.back() == ' ')) path.pop_back();
                  if (path.substr(0, 7) == "http://" || path.substr(0, 8) == "https://") {
                    return path;
                  }
                  return id(ha_base_url) + path;

  - platform: template
    id: media_player_state_sensor
    on_value:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode);'
          then:
            - if:
                condition:
                  lambda: 'return x == "playing";'
                then:
                  - script.stop: backlight_wake_timeout
                  - lvgl.resume:
                  - lvgl.widget.hide:
                      id: media_play_icon
                  - lvgl.widget.show:
                      id: media_pause_icon
                  - light.turn_on:
                      id: backlight
                      brightness: 100%
                  - if:
                      condition:
                        lambda: 'return id(is_screen_dimmed);'
                      then:
                        - lambda: 'id(is_screen_dimmed) = false;'
                        - script.execute: show_track_view
                  - script.execute: auto_hide_track_info
                else:
                  - script.stop: auto_hide_track_info
                  - script.execute: show_track_view
                  - lvgl.widget.show:
                      id: media_play_icon
                  - lvgl.widget.hide:
                      id: media_pause_icon
                  - script.execute: backlight_wake_timeout

  # HA reports media_position as of media_position_updated_at (often seconds stale).
  # Parse the UTC timestamp so the interval timer can compensate for staleness.
  - platform: template
    id: media_position_updated_at_sensor
    on_value:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode);'
          then:
            - lambda: |-
                int yr, mo, dy, hr, mn, sc;
                if (sscanf(x.c_str(), "%d-%d-%dT%d:%d:%d", &yr, &mo, &dy, &hr, &mn, &sc) != 6 &&
                    sscanf(x.c_str(), "%d-%d-%d %d:%d:%d", &yr, &mo, &dy, &hr, &mn, &sc) != 6) {
                  return;
                }
                int y = yr, m = mo;
                if (m <= 2) { y--; m += 12; }
                long days = 365L*y + y/4 - y/100 + y/400 + (153*(m-3)+2)/5 + dy - 719469;
                int epoch = (int)(days * 86400L + hr * 3600 + mn * 60 + sc);
                id(ha_position_epoch) = epoch;
                if (id(media_position_sensor).has_state()) {
                  id(last_position_timestamp) = epoch;
                }

  - platform: template
    id: media_source_sensor
    on_value:
      - if:
          condition:
            lambda: 'return x == "TV" && !id(is_tv_mode);'
          then:
            - script.execute: enter_tv_mode
      - if:
          condition:
            lambda: 'return x != "TV" && id(is_tv_mode);'
          then:
            - script.execute: exit_tv_mode

sensor:
  - platform: template
    id: media_duration_sensor

  - platform: template
    id: media_position_sensor
    on_value:
      - if:
          condition:
            lambda: 'return !id(is_tv_mode);'
          then:
            - lambda: |-
                id(last_media_position) = x;
                if (id(ha_position_epoch) != 0) {
                  id(last_position_timestamp) = id(ha_position_epoch);
                } else {
                  auto t = id(ha_time).now();
                  if (t.is_valid()) id(last_position_timestamp) = t.timestamp;
                }

  - platform: template
    id: media_volume_sensor
    on_value:
      - lvgl.arc.update:
          id: volume_arc
          value: !lambda 'return (int)(x * 100.0f);'
      - lvgl.label.update:
          id: volume_pct_label
          text: !lambda |-
            char buf[8];
            snprintf(buf, sizeof(buf), "%d%%", (int)(x * 100.0f));
            return std::string(buf);


# -----------------------------------------------------------------------------
# USER-CONFIGURABLE SETTINGS (exposed to Home Assistant)
# -----------------------------------------------------------------------------
# How long track info (title, artist, time, play/pause) stays visible after
# a track change before auto-hiding. Set to 0 to keep info always visible.
# -----------------------------------------------------------------------------
number:
  - platform: template
    name: "Track Info Duration"
    id: track_info_duration
    min_value: 0
    max_value: 60
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true
    unit_of_measurement: "s"
    icon: "mdi:timer-outline"
    entity_category: config
    mode: box
